name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 19
          - 20
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: === PROCURE NODE ${{ matrix.node }} ===
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: === CHECK OUT ===
        uses: actions/checkout@v3

      - name: === CACHE/RESTORE 3RD PARTY DEPS ===
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: node-modules
        with:
          path: node_modules/
          key: ${{ env.cache-name }}-node-version-${{ matrix.node }}-os-${{ matrix.os }}-lockfile-hash-${{ hashFiles('**/package-lock.json') }}

      - name: === INSTALL DEPS ===
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: npm i

      - name: === PREPARE ENV FILE  ===
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cat <<EOT >> .env
          UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          EOT

      - name: === PREPARE ENV FILE (WINDOWS) ===
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}" | Out-File -FilePath '.env' -Encoding utf8 -Append
          echo "UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" | Out-File -FilePath '.env' -Encoding utf8 -Append

      - name: === LINT & TEST ===
        run: npm run check
